


// users

GET http://localhost:8080/users

###
GET http://localhost:8080/users/1

###
GET http://localhost:8080/userEvent/1

###
PUT http://localhost:8080/users/1
Content-Type: application/json

{
	"name": "andres",
	"email": "andres@gmail.com",
	"country": "rusia",
	"role": "owner"
}

###
DELETE http://localhost:8080/users/7


// events

###
GET http://localhost:8080/events
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaGVjayI6dHJ1ZSwiaWF0IjoxNTg5OTM2Nzc1LCJleHAiOjE1ODk5MzY4NzV9.cMw7D83EP1qIpZxN561nbMBofU59FK-sJXKN_7x4ysY

###
GET http://localhost:8080/events/12
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaGVjayI6dHJ1ZSwiaWF0IjoxNTg5OTM2Nzc1LCJleHAiOjE1ODk5MzY4NzV9.cMw7D83EP1qIpZxN561nbMBofU59FK-sJXKN_7x4ysY

###
POST http://localhost:8080/events
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaGVjayI6dHJ1ZSwiaWF0IjoxNTg5OTMzMjk4LCJleHAiOjE1ODk5MzQ3Mzh9.6DKJ2n5aZXWvOqRsqX-tj4cNk2oAFNngtzIXWIcyLDY

{
    "title": "Angular Meet",
    "description": "lorem ipsum details france",
    "picture": "https://www.kindpng.com/picc/m/73-737324_abstract-submission-nutrition-congress-circle-meeting-icon-png.png",
    "id_user": 1,
    "latitude": "37.78825",
    "longitude": "-122.4324",
    "latitude_delta": "0.0922",
    "longitude_delta": "0.0421"
}

###
PUT http://localhost:8080/events/9
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaGVjayI6dHJ1ZSwiaWF0IjoxNTg5OTMzMjk4LCJleHAiOjE1ODk5MzQ3Mzh9.6DKJ2n5aZXWvOqRsqX-tj4cNk2oAFNngtzIXWIcyLDY

{
   "title": "Android Meet",
    "description": "lorem ipsum details france",
    "picture": "https://www.kindpng.com/picc/m/73-737324_abstract-submission-nutrition-congress-circle-meeting-icon-png.png",
    "id_user": 1,
    "latitude": "37.78825",
    "longitude": "-122.4324",
    "latitude_delta": "0.0922",
    "longitude_delta": "0.0421"
}

###
DELETE http://localhost:8080/events/7
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaGVjayI6dHJ1ZSwiaWF0IjoxNTg5OTMzMjk4LCJleHAiOjE1ODk5MzQ3Mzh9.6DKJ2n5aZXWvOqRsqX-tj4cNk2oAFNngtzIXWIcyLDY



###
POST http://localhost:8080/auth/getToken
Content-Type: application/json

{
    "email": "wilfrido@gmail.com",
    "password": "123456"
}

###
GET http://localhost:8080/auth/getToken

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
	"name": "wilfrido",
	"email": "wilfridobonett@gmail.com",
	"country": "rusia",
	"password": "123456",
    "username": "wbonett"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaGVjayI6dHJ1ZSwiaWF0IjoxNTg5OTMzMjk4LCJleHAiOjE1ODk5MzQ3Mzh9.6DKJ2n5aZXWvOqRsqX-tj4cNk2oAFNngtzIXWIcyLDY

{
	"email": "andres@gmail.com",
    "password": "12345"
}