


// users

GET http://localhost:8080/users

###
GET http://localhost:8080/users/1

###
GET http://localhost:8080/userEvent/1

###
POST http://localhost:8080/users
Content-Type: application/json

{
	"name": "andres",
	"email": "andres@gmail.com",
	"country": "rusia",
	"role": "owner"
}

###
PUT http://localhost:8080/users/1
Content-Type: application/json

{
	"name": "andres",
	"email": "andres@gmail.com",
	"country": "rusia",
	"role": "owner"
}

###
DELETE http://localhost:8080/users/1


// events

###
GET http://localhost:8080/events

###
GET http://localhost:8080/events/9

###
POST http://localhost:8080/events
Content-Type: application/json

{
    "title": "Angular Meet",
    "description": "lorem ipsum details france",
    "picture": "https://www.kindpng.com/picc/m/73-737324_abstract-submission-nutrition-congress-circle-meeting-icon-png.png",
    "id_user": 1,
    "latitude": "37.78825",
    "longitude": "-122.4324",
    "latitude_delta": "0.0922",
    "longitude_delta": "0.0421"
}

###
PUT http://localhost:8080/events/9
Content-Type: application/json

{
   "title": "Android Meet",
    "description": "lorem ipsum details france",
    "picture": "https://www.kindpng.com/picc/m/73-737324_abstract-submission-nutrition-congress-circle-meeting-icon-png.png",
    "id_user": 1,
    "latitude": "37.78825",
    "longitude": "-122.4324",
    "latitude_delta": "0.0922",
    "longitude_delta": "0.0421"
}

###
DELETE http://localhost:8080/events/7